// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh9qE-BFtlzAAv7Hj_bP1AO26_q7ArxUs',
    appId: '1:135394790224:web:743480ed368a959c8b3a55',
    messagingSenderId: '135394790224',
    projectId: 'fasum-app-2d521',
    authDomain: 'fasum-app-2d521.firebaseapp.com',
    storageBucket: 'fasum-app-2d521.appspot.com',
    measurementId: 'G-MPTHKMKEFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0mOgYolLO8FJscTAMDgCzlGvsUZh5s24',
    appId: '1:135394790224:android:fa3ba1268ae7f7128b3a55',
    messagingSenderId: '135394790224',
    projectId: 'fasum-app-2d521',
    storageBucket: 'fasum-app-2d521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSft1O2jtK1TWAE3ukRVXr_6eqkefNSf8',
    appId: '1:135394790224:ios:b6659a4094fbe6a98b3a55',
    messagingSenderId: '135394790224',
    projectId: 'fasum-app-2d521',
    storageBucket: 'fasum-app-2d521.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSft1O2jtK1TWAE3ukRVXr_6eqkefNSf8',
    appId: '1:135394790224:ios:42402c1bdbbd61a48b3a55',
    messagingSenderId: '135394790224',
    projectId: 'fasum-app-2d521',
    storageBucket: 'fasum-app-2d521.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
